import jsPDF from "jspdf";
// import html2canvas from "html2canvas";
import { useState, useEffect } from "react";
import { useParams, useNavigate } from "react-router-dom";
import axiosInstance from "../utils/axiosInstance";

const SessionPage = () => {
  const { id } = useParams();
  const navigate = useNavigate();

  const [session, setSession] = useState(null);
  const [questions, setQuestions] = useState([]);
  const [loading, setLoading] = useState(true);
  const [openId, setOpenId] = useState(null);
  const [explanation, setExplanation] = useState({ id: null, text: "", loading: false });
  const [noteEdit, setNoteEdit] = useState({ id: null, text: "" });
  const [filter, setFilter] = useState("all"); // all | pinned

  useEffect(() => {
    const fetchSession = async () => {
      try {
        const res = await axiosInstance.get(`/sessions/${id}`);
        setSession(res.data.session);
        setQuestions(res.data.questions);
      } catch (err) {
        console.error("Failed to fetch session", err);
      } finally {
        setLoading(false);
      }
    };
    fetchSession();
  }, [id]);

  // Toggle accordion
  const toggleAccordion = (qId) => {
    setOpenId(openId === qId ? null : qId);
  };

  // Toggle pin
  const handlePin = async (qId, e) => {
    e.stopPropagation();
    try {
      const res = await axiosInstance.put(`/sessions/questions/${qId}/pin`);
      setQuestions(questions.map((q) => (q._id === qId ? res.data : q)));
    } catch (err) {
      console.error("Pin failed", err);
    }
  };

  // Get AI Explanation
  const handleExplain = async (qId, e) => {
    e.stopPropagation();
    if (explanation.id === qId) {
      setExplanation({ id: null, text: "", loading: false });
      return;
    }
    setExplanation({ id: qId, text: "", loading: true });
    try {
      const res = await axiosInstance.get(`/sessions/questions/${qId}/explain`);
      setExplanation({ id: qId, text: res.data.explanation, loading: false });
    } catch (err) {
      setExplanation({ id: qId, text: "Failed to get explanation.", loading: false });
    }
  };

  // Save Note
  const handleSaveNote = async (qId) => {
    try {
      const res = await axiosInstance.put(`/sessions/questions/${qId}/note`, {
        note: noteEdit.text,
      });
      setQuestions(questions.map((q) => (q._id === qId ? res.data : q)));
      setNoteEdit({ id: null, text: "" });
    } catch (err) {
      console.error("Note save failed", err);
    }
  };

  const filtered = filter === "pinned"
    ? questions.filter((q) => q.isPinned)
    : questions;

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center text-white text-xl"
        style={{ background: "linear-gradient(135deg, #0f0c29, #302b63, #24243e)" }}>
        ⏳ Loading session...
      </div>
    );
  }

// PDF handling method
const handleExportPDF = () => {
  const pdf = new jsPDF("p", "mm", "a4");
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const margin = 15;
  const maxWidth = pageWidth - margin * 2;
  let y = 20;

  const checkNewPage = (neededHeight) => {
    if (y + neededHeight > pageHeight - 20) {
      pdf.addPage();
      y = 20;
    }
  };

  // ── Header ──
  pdf.setFillColor(15, 12, 41);
  pdf.rect(0, 0, pageWidth, 30, "F");
  pdf.setTextColor(255, 211, 0);
  pdf.setFontSize(20);
  pdf.setFont("helvetica", "bold");
  pdf.text("PrepAI", margin, 18);
  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(11);
  pdf.text("AI-Powered Interview Preparation", margin + 28, 18);
  y = 40;

  // ── Session Info ──
  pdf.setTextColor(30, 30, 60);
  pdf.setFontSize(16);
  pdf.setFont("helvetica", "bold");
  pdf.text(`${session?.role} — Interview Q&A`, margin, y);
  y += 8;

  pdf.setFontSize(10);
  pdf.setFont("helvetica", "normal");
  pdf.setTextColor(100, 100, 130);
  pdf.text(`Experience: ${session?.experience}   |   Total Questions: ${questions.length}   |   Generated by PrepAI`, margin, y);
  y += 6;

  // Divider line
  pdf.setDrawColor(200, 200, 220);
  pdf.line(margin, y, pageWidth - margin, y);
  y += 10;

  // ── Questions & Answers ──
  questions.forEach((q, index) => {
    checkNewPage(20);

    // Question number badge background
    pdf.setFillColor(79, 70, 229);
    pdf.roundedRect(margin, y - 5, 8, 8, 1, 1, "F");
    pdf.setTextColor(255, 255, 255);
    pdf.setFontSize(8);
    pdf.setFont("helvetica", "bold");
    pdf.text(`${index + 1}`, margin + 2.5, y + 0.5);

    // Question text
    pdf.setTextColor(20, 20, 60);
    pdf.setFontSize(11);
    pdf.setFont("helvetica", "bold");
    const questionLines = pdf.splitTextToSize(`${q.question}`, maxWidth - 12);
    pdf.text(questionLines, margin + 12, y);
    y += questionLines.length * 6 + 4;

    // Pinned badge
    if (q.isPinned) {
      checkNewPage(8);
      pdf.setFillColor(255, 211, 0);
      pdf.roundedRect(margin + 12, y - 4, 18, 6, 1, 1, "F");
      pdf.setTextColor(30, 30, 60);
      pdf.setFontSize(7);
      pdf.setFont("helvetica", "bold");
      pdf.text("PINNED", margin + 14, y);
      y += 6;
    }

    // Answer label
    checkNewPage(10);
    pdf.setFillColor(240, 240, 255);
    pdf.rect(margin, y, maxWidth, 6, "F");
    pdf.setTextColor(79, 70, 229);
    pdf.setFontSize(8);
    pdf.setFont("helvetica", "bold");
    pdf.text("ANSWER", margin + 2, y + 4);
    y += 8;

    // Answer text
    pdf.setTextColor(50, 50, 80);
    pdf.setFontSize(9.5);
    pdf.setFont("helvetica", "normal");
    const answerLines = pdf.splitTextToSize(q.answer, maxWidth - 4);
    answerLines.forEach((line) => {
      checkNewPage(6);
      pdf.text(line, margin + 2, y);
      y += 5.5;
    });

    // Note (if exists)
    if (q.note) {
      checkNewPage(12);
      y += 2;
      pdf.setFillColor(255, 240, 250);
      const noteLines = pdf.splitTextToSize(`Note: ${q.note}`, maxWidth - 4);
      pdf.rect(margin, y - 3, maxWidth, noteLines.length * 5.5 + 6, "F");
      pdf.setTextColor(180, 60, 120);
      pdf.setFontSize(8.5);
      pdf.setFont("helvetica", "italic");
      noteLines.forEach((line) => {
        pdf.text(line, margin + 2, y);
        y += 5.5;
      });
    }

    // Divider between questions
    y += 6;
    checkNewPage(4);
    pdf.setDrawColor(220, 220, 235);
    pdf.line(margin, y, pageWidth - margin, y);
    y += 8;
  });

  // ── Footer on last page ──
  pdf.setFontSize(8);
  pdf.setTextColor(160, 160, 180);
  pdf.text(
    `Generated by PrepAI • ${new Date().toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" })}`,
    margin,
    pageHeight - 10
  );

  pdf.save(`${session?.role}-PrepAI-Interview.pdf`);
};

  return (
    <div className="min-h-screen text-white"
      style={{ background: "linear-gradient(135deg, #0f0c29, #302b63, #24243e)" }}>

      {/* ── Navbar ── */}
      <nav className="bg-white/10 backdrop-blur-md border-b border-white/20 px-8 py-4 flex justify-between items-center sticky top-0 z-50">
        <h1 className="text-2xl font-extrabold text-white">
          Prep<span className="text-yellow-300">AI</span>
        </h1>
        <button
          onClick={() => navigate("/dashboard")}
          className="bg-white/10 border border-white/20 px-4 py-2 rounded-xl text-sm hover:bg-white/20 transition"
        >
          ← Back to Dashboard
        </button>

        {/* Export button below */}
    <button
  onClick={handleExportPDF}
  className="bg-gradient-to-r from-yellow-300 to-pink-400 text-indigo-900 font-bold px-4 py-2 rounded-xl text-sm hover:scale-105 transition-transform"
>
  ⬇ Export PDF
</button>

      </nav>

      <div className="max-w-6xl mx-auto px-6 py-10">

        {/* Session Info */}
        <div className="mb-8">
          <span className="inline-block bg-yellow-300/20 text-yellow-300 text-xs font-bold px-4 py-1 rounded-full mb-3 tracking-widest uppercase">
            {session?.experience} Experience
          </span>
          <h2 className="text-4xl font-extrabold mb-2">
            {session?.role}{" "}
            <span className="text-transparent bg-clip-text bg-gradient-to-r from-yellow-300 to-pink-400">
              Interview Prep
            </span>
          </h2>
          {session?.description && (
            <p className="text-white/50">{session.description}</p>
          )}
        </div>

        {/* Filter Tabs */}
        <div className="flex gap-3 mb-8">
          <button
            onClick={() => setFilter("all")}
            className={`px-5 py-2 rounded-full text-sm font-semibold transition ${
              filter === "all"
                ? "bg-gradient-to-r from-yellow-300 to-pink-400 text-indigo-900"
                : "bg-white/10 text-white/70 hover:bg-white/20"
            }`}
          >
            All Questions ({questions.length})
          </button>
          <button
            onClick={() => setFilter("pinned")}
            className={`px-5 py-2 rounded-full text-sm font-semibold transition ${
              filter === "pinned"
                ? "bg-gradient-to-r from-yellow-300 to-pink-400 text-indigo-900"
                : "bg-white/10 text-white/70 hover:bg-white/20"
            }`}
          >
            📌 Pinned ({questions.filter((q) => q.isPinned).length})
          </button>
        </div>

        {/* Two Column Layout ,id for wrapping content to download as PDF*/}
        <div className="flex gap-6" id="qa-content">

          {/* ── Left: Accordion Q&A ── */}
          <div className="flex-1 space-y-4">
            {filtered.length === 0 ? (
              <div className="text-center py-16 text-white/40">
                <div className="text-5xl mb-3">📌</div>
                <p>No pinned questions yet. Pin questions to see them here!</p>
              </div>
            ) : (
              filtered.map((q, index) => (
                <div key={q._id}
                  className={`bg-white/10 backdrop-blur border rounded-2xl overflow-hidden transition-all ${
                    q.isPinned ? "border-yellow-300/50" : "border-white/10"
                  }`}>

                  {/* Question Header */}
                  <div
                    onClick={() => toggleAccordion(q._id)}
                    className="flex justify-between items-center px-6 py-4 cursor-pointer hover:bg-white/5 transition"
                  >
                    <div className="flex items-center gap-3 flex-1">
                      <span className="text-yellow-300 font-black text-sm min-w-[28px]">
                        {index + 1}.
                      </span>
                      <p className="text-white font-semibold text-sm leading-snug">
                        {q.question}
                      </p>
                    </div>
                    <div className="flex items-center gap-2 ml-4 shrink-0">
                      {/* Pin Button */}
                      <button
                        onClick={(e) => handlePin(q._id, e)}
                        className={`text-xs px-3 py-1 rounded-full transition ${
                          q.isPinned
                            ? "bg-yellow-300/30 text-yellow-300"
                            : "bg-white/10 text-white/50 hover:text-yellow-300"
                        }`}
                      >
                        {q.isPinned ? "📌 Pinned" : "📌 Pin"}
                      </button>
                      {/* Expand Arrow */}
                      <span className="text-white/40 text-lg">
                        {openId === q._id ? "▲" : "▼"}
                      </span>
                    </div>
                  </div>

                  {/* Accordion Body */}
                  {openId === q._id && (
                    <div className="px-6 pb-6 border-t border-white/10">

                      {/* Answer */}
                      <div className="mt-4 bg-white/5 rounded-xl p-4">
                        <p className="text-white/40 text-xs font-bold uppercase mb-2 tracking-widest">
                          Answer
                        </p>
                        <p className="text-white/80 text-sm leading-relaxed whitespace-pre-line">
                          {q.answer}
                        </p>
                      </div>

                      {/* Action Buttons */}
                      <div className="flex gap-3 mt-4 flex-wrap">
                        <button
                          onClick={(e) => handleExplain(q._id, e)}
                          className="bg-indigo-500/30 hover:bg-indigo-500/50 text-indigo-200 text-xs font-semibold px-4 py-2 rounded-full transition"
                        >
                          {explanation.id === q._id ? "✕ Close Explanation" : "💡 Explain Simply"}
                        </button>
                        <button
                          onClick={() =>
                            setNoteEdit(
                              noteEdit.id === q._id
                                ? { id: null, text: "" }
                                : { id: q._id, text: q.note || "" }
                            )
                          }
                          className="bg-pink-500/30 hover:bg-pink-500/50 text-pink-200 text-xs font-semibold px-4 py-2 rounded-full transition"
                        >
                          {noteEdit.id === q._id ? "✕ Close Note" : "📝 Add Note"}
                        </button>
                      </div>

                      {/* AI Explanation Panel */}
                      {explanation.id === q._id && (
                        <div className="mt-4 bg-indigo-500/10 border border-indigo-400/30 rounded-xl p-4">
                          <p className="text-indigo-300 text-xs font-bold uppercase mb-2 tracking-widest">
                            💡 AI Explanation
                          </p>
                          {explanation.loading ? (
                            <p className="text-white/50 text-sm animate-pulse">
                              Generating explanation...
                            </p>
                          ) : (
                            <p className="text-white/80 text-sm leading-relaxed whitespace-pre-line">
                              {explanation.text}
                            </p>
                          )}
                        </div>
                      )}

                      {/* Note Panel */}
                      {noteEdit.id === q._id && (
                        <div className="mt-4 bg-pink-500/10 border border-pink-400/30 rounded-xl p-4">
                          <p className="text-pink-300 text-xs font-bold uppercase mb-2 tracking-widest">
                            📝 Your Note
                          </p>
                          <textarea
                            rows={3}
                            value={noteEdit.text}
                            onChange={(e) =>
                              setNoteEdit({ ...noteEdit, text: e.target.value })
                            }
                            placeholder="Write your note here..."
                            className="w-full bg-white/10 border border-white/20 rounded-xl px-4 py-2 text-white placeholder-white/30 text-sm focus:outline-none focus:ring-2 focus:ring-pink-300 resize-none"
                          />
                          <button
                            onClick={() => handleSaveNote(q._id)}
                            className="mt-2 bg-gradient-to-r from-pink-400 to-yellow-300 text-indigo-900 font-bold text-xs px-5 py-2 rounded-full hover:scale-105 transition-transform"
                          >
                            Save Note
                          </button>
                        </div>
                      )}

                      {/* Saved Note Display */}
                      {q.note && noteEdit.id !== q._id && (
                        <div className="mt-4 bg-pink-500/10 border border-pink-400/20 rounded-xl p-4">
                          <p className="text-pink-300 text-xs font-bold uppercase mb-1 tracking-widest">
                            📝 Your Note
                          </p>
                          <p className="text-white/70 text-sm">{q.note}</p>
                        </div>
                      )}
                    </div>
                  )}
                </div>
              ))
            )}
          </div>

          {/* ── Right: Session Summary Card ── */}
          <div className="w-72 shrink-0 hidden lg:block">
            <div className="bg-white/10 backdrop-blur border border-white/10 rounded-2xl p-6 sticky top-24">
              <h3 className="text-lg font-extrabold text-white mb-4">
                Session <span className="text-yellow-300">Summary</span>
              </h3>
              <div className="space-y-3">
                <div className="flex justify-between text-sm">
                  <span className="text-white/50">Role</span>
                  <span className="text-white font-semibold">{session?.role}</span>
                </div>
                <div className="flex justify-between text-sm">
                  <span className="text-white/50">Experience</span>
                  <span className="text-white font-semibold">{session?.experience}</span>
                </div>
                <div className="flex justify-between text-sm">
                  <span className="text-white/50">Total Q&A</span>
                  <span className="text-yellow-300 font-bold">{questions.length}</span>
                </div>
                <div className="flex justify-between text-sm">
                  <span className="text-white/50">Pinned</span>
                  <span className="text-yellow-300 font-bold">
                    {questions.filter((q) => q.isPinned).length}
                  </span>
                </div>
                <div className="flex justify-between text-sm">
                  <span className="text-white/50">Notes Added</span>
                  <span className="text-pink-300 font-bold">
                    {questions.filter((q) => q.note).length}
                  </span>
                </div>
                <div className="flex justify-between text-sm">
                  <span className="text-white/50">Created</span>
                  <span className="text-white/70 text-xs">
                    {new Date(session?.createdAt).toLocaleDateString("en-IN", {
                      day: "numeric", month: "short", year: "numeric"
                    })}
                  </span>
                </div>
              </div>

              <div className="mt-6 pt-4 border-t border-white/10">
                <button
                  onClick={() => setFilter(filter === "pinned" ? "all" : "pinned")}
                  className="w-full bg-yellow-300/20 text-yellow-300 font-semibold py-2 rounded-xl text-sm hover:bg-yellow-300/30 transition"
                >
                  {filter === "pinned" ? "Show All" : "📌 Show Pinned Only"}
                </button>
                <button
                  onClick={() => navigate("/dashboard")}
                  className="w-full mt-2 bg-white/10 text-white/70 font-semibold py-2 rounded-xl text-sm hover:bg-white/20 transition"
                >
                  ← Back to Dashboard
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default SessionPage;